name = "Cthonios"
uuid = "a67e86c2-42a5-4f10-921b-1e94bb8ae306"
authors = ["Craig M. Hamel <cmhamel32@gmail.com> and contributors"]
version = "0.3.1"

[deps]
ArgParse = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"
Arpack = "7d9fca2a-8960-54d3-9f78-7d1dccf2cb97"
ConstitutiveModels = "fc6ee7eb-129a-416f-804b-d7271ece6a3a"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
Enzyme = "7da242da-08ed-463a-9acd-ee780be4f1d9"
Exodus = "f57ae99e-f805-4780-bdca-96e224be1e5a"
FiniteElementContainers = "d08262e4-672f-4e7f-a976-f2cea5767631"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"
Krylov = "ba0b0d4f-ebba-5204-a429-3ac8c609bfb7"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NLopt = "76087f3c-5699-56af-9a33-bf431cd00edd"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
ReferenceFiniteElements = "6dc62d09-f8eb-43fd-9672-074e490a997f"
RuntimeGeneratedFunctions = "7e49a35a-f44a-4d26-94aa-eba1b4ca6b47"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
StructArrays = "09ab397b-f2b6-538f-b94a-2f83cf4a842a"
Tensors = "48a634ad-e948-5137-8d70-aa71f2a747f4"
TimerOutputs = "a759f4b9-e2f1-59dc-863e-4aeb61b1ea8f"
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"

[weakdeps]
AMDGPU = "21141c5a-9bdb-4563-92ae-f87d6854732e"

[extensions]
CthoniosAMDGPUExt = "AMDGPU"

[compat]
AMDGPU = "1"
Aqua = "0.8"
ArgParse = "1"
Arpack = "0.5"
ConstitutiveModels = "0.2"
DocStringExtensions = "0.9"
Enzyme = "0.13"
Exodus = "0.14"
FiniteElementContainers = "0.9"
ForwardDiff = "1"
KernelAbstractions = "0.9"
Krylov = "0.9"
LinearAlgebra = "1"
NLopt = "1"
Printf = "1"
ReferenceFiniteElements = "0.13"
RuntimeGeneratedFunctions = "0.5"
SparseArrays = "1"
StaticArrays = "1"
StructArrays = "0.7"
Tensors = "1"
Test = "1"
TimerOutputs = "0.5"
YAML = "0.4"
julia = "1"

[apps.cthonios-dev]

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "Test"]
